# Generated by Django 2.2.14 on 2021-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_uri',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'T-Shirt'), ('SW', 'Sportswear'), ('FW', 'Footwear'), ('SA', 'Sports Accessories')], max_length=2),
        ),
    ]
