# Generated by Django 2.2.14 on 2021-01-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210103_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_uri',
        ),
    ]
